#!/usr/bin/perl

use Astro::MoonPhase;
use POSIX 'strftime';

my $t = time() + shift() * 86_400;

my ($MoonPhase) = sprintf "%.0f", phase($t) * 100;

my @phaseDesc = qw(new 1stq full lastq);
my ($phase, @times) = phaselist($t, $t + 30 * 86_400);

print "Subject: The moon is $MoonPhase% full\n\n";
print "($phaseDesc[($phase+3)%4] moon)\n\n";
for (0 .. $#times) {
  print strftime($phaseDesc[($phase + $_) % 4] . ": %a %e %b\n",
                 localtime($times[$_]));
}

